name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    
    - uses: actions/checkout@v1
    - name: Show dir for debug
      run: ls -la
  
    - name: build Consul
      run: make linux
      
    - name: check results
      run: ./consul version
      
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: consul-binary
        path: consul
