name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - uses: actions/checkout@v1
    
    - name: build Consul
      run: export GOPATH=/home/runner/work/consul/consul && make tools && make linux

    - name: check results
      run: export GOPATH=/home/runner/work/consul/consul && pwd && echo $GOPATH && ls $GOPATH/bin 
      
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: consul-binary
        path: $GOPATH/bin/consul
